let add_i a b = a + b
let sub_i a b = a - b
let mult_i a b = a * b
let div_i a b = a / b
let add_f a b = a +. b
let sub_f a b = a -. b
let mult_f a b = a *. b
let div_f a b = a /. b
let inverse a = 1. /. a
let square a = a *. a
let sqrt a = a ** 0.5
let log a = Float.log10 a
let ten_x a = 10. ** a
let ln a = Float.log a
let exp a = Float.exp a
let pi = Float.pi
let e = Float.exp 1.
